---
- name: Check if Docker service is running
  ansible.builtin.service_facts:

- name: Ensure Docker service is running
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
  when: "'docker' not in ansible_facts.services or ansible_facts.services['docker'].state != 'running'"

